### ISSUE TITLE
Choosing app & variant before building

### ISSUE THREAD

**Issue by ManorSailor** [n0k0m3/revanced-build-template#53]
Hey @n0k0m3 . I have been working on a feature to allow user the ability to choose which app they want to build (Yt ot ytm) & also which variant they want to build (root or non root). You can see the progress [here](https://github.com/ManorSailor/revanced-build-template/commits/config). I am opening this issue to understand how this feature can be better implemented and also to receive your feedback on stuff you would like to see changed. If you feel like it's alright, I will open a PR

Let me know what you think.

**Comment by missemily2022** [comment]
@ManorSailor I would like to suggest something.The place where people have to edit the .config file to include their preferences - I guess it would be easier if adding a secret with Variable Name and Value would server the job because it prevents users making unnecessary commits and also we can automatically update the Forms with Original if peeps are made to do no commit

On a second note, I would also suggest if the same Secrets option could be done for excluding or including patches and the reason is same that it would prevent Unnecessary commits which breaks the ability to update forks easily.

Thanks for your time 🤠 :)

**Comment by ManorSailor** [comment]
@missemily2022 

> I guess it would be easier if adding a secret with Variable Name and Value would server the job

Can you elaborate on this further? I don't understand what you mean.

Thank you :)

**Comment by missemily2022** [comment]
@ManorSailor I meant to say that instead of editing files via committing in GitHub can the same be done by adding/updating GitHub Secrets so that unnecessary commits are avoided.

**Comment by missemily2022** [comment]
@ManorSailor I meant to say that instead of editing files via committing in GitHub can the same be done by adding/updating GitHub Secrets

**Comment by ManorSailor** [comment]
@missemily2022 I see. Unfortunately, I have no idea how that will work as I've never used GitHub secrets before @_@

If you can guide me in the right direction, I'll take a look at it & see what can be done.

**Comment by missemily2022** [comment]
@ManorSailor You want an example of how Github Secrets work? Right?

**Comment by ManorSailor** [comment]
> @ManorSailor You want an example of how Github Secrets work? Right?

Yes
