### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by gosndka** [n0k0m3/revanced-build-template#63]
Since revanced group is also doing spotify would you mind adding the spotify to your code? So that we can build revanced spotify.

**Comment by SCP-017** [comment]
@gosndka 

I think you should do it manually, I mean add that feature to your repo. Since his/her repo focuses on downloading the applications in APK Mirror, there will be a lot of work adding the Spotify in the code because the APK Mirror doesn't have the Spotify application.

For me, I brought back the UpToDown download script that is used here from before it is changed to APK Mirror download script. That script downloads the Spotify from UpToDown instead on APK Mirror. I didn't put the version selection code with it so it downloads the latest version of Spotify, but you can add that if you want.

If you want, I can give you the example script that I'm using right now.

**Comment by n0k0m3** [comment]
I don't see any desired feature from revanced spotify patches comparing to XManager (https://github.com/xManager-v2/xManager-Spotify). Will close this issue but feel free to keep discussing

**Comment by gosndka** [comment]
> @gosndka
> 
> I think you should do it manually, I mean add that feature to your repo. Since his/her repo focuses on downloading the applications in APK Mirror, there will be a lot of work adding the Spotify in the code because the APK Mirror doesn't have the Spotify application.
> 
> For me, I brought back the UpToDown download script that is used here from before it is changed to APK Mirror download script. That script downloads the Spotify from UpToDown instead on APK Mirror. I didn't put the version selection code with it so it downloads the latest version of Spotify, but you can add that if you want.
> 
> If you want, I can give you the example script that I'm using right now.

I have no coding knowledge at all so I can't really create a script to download it from uptodown.

**Comment by SCP-017** [comment]
@gosndka 

Check this script, maybe it can help you :

https://raw.githubusercontent.com/SCP-017/debug/main/main/spotify/download.sh

The script is from my repo here :
https://github.com/SCP-017/debug

(I also have no coding knowledge and I just made my repo from other's scripts/repo.)
